export const categories = [
  {
    id: '1',
    name: 'Fruit & Vegetable',
    image: require("../../../assets/homepage/category/vegitable.png"),
    products: [
      { id: '1-1', name: 'Apple', price: 120, discountPrice: 110, image: 'https://via.placeholder.com/100' },
      { id: '1-2', name: 'Banana', price: 40, discountPrice: 35, image: 'https://via.placeholder.com/100' },
      { id: '1-3', name: 'Tomato', price: 30, discountPrice: 25, image: 'https://via.placeholder.com/100' },
      { id: '1-4', name: 'Carrot', price: 50, discountPrice: 45, image: 'https://via.placeholder.com/100' },
      { id: '1-5', name: 'Orange', price: 60, discountPrice: 55, image: 'https://via.placeholder.com/100' },
      { id: '1-6', name: 'Broccoli', price: 70, discountPrice: 65, image: 'https://via.placeholder.com/100' },
      { id: '1-7', name: 'Spinach', price: 40, discountPrice: 35, image: 'https://via.placeholder.com/100' },
      { id: '1-8', name: 'Potato', price: 25, discountPrice: 20, image: 'https://via.placeholder.com/100' },
      { id: '1-9', name: 'Onion', price: 30, discountPrice: 28, image: 'https://via.placeholder.com/100' },
      { id: '1-10', name: 'Grapes', price: 150, discountPrice: 140, image: 'https://via.placeholder.com/100' },
    ],
  },
  {
    id: '2',
    name: 'Cooking Oil & Ghee',
    image: require("../../../assets/homepage/category/oil.png"),
    products: [
      { id: '2-1', name: 'Olive Oil', price: 500, discountPrice: 450, image: 'https://via.placeholder.com/100' },
      { id: '2-2', name: 'Sunflower Oil', price: 200, discountPrice: 180, image: 'https://via.placeholder.com/100' },
      { id: '2-3', name: 'Ghee', price: 400, discountPrice: 360, image: 'https://via.placeholder.com/100' },
      { id: '2-4', name: 'Coconut Oil', price: 300, discountPrice: 270, image: 'https://via.placeholder.com/100' },
      { id: '2-5', name: 'Sesame Oil', price: 250, discountPrice: 230, image: 'https://via.placeholder.com/100' },
      { id: '2-6', name: 'Avocado Oil', price: 600, discountPrice: 550, image: 'https://via.placeholder.com/100' },
      { id: '2-7', name: 'Canola Oil', price: 180, discountPrice: 160, image: 'https://via.placeholder.com/100' },
      { id: '2-8', name: 'Mustard Oil', price: 220, discountPrice: 200, image: 'https://via.placeholder.com/100' },
      { id: '2-9', name: 'Almond Oil', price: 700, discountPrice: 650, image: 'https://via.placeholder.com/100' },
      { id: '2-10', name: 'Palm Oil', price: 350, discountPrice: 320, image: 'https://via.placeholder.com/100' },
    ],
  },
  {
    id: '3',
    name: 'Meat & Fish',
    image: require("../../../assets/homepage/category/meat.png"),
    products: [
      { id: '3-1', name: 'Chicken Breast', price: 250, discountPrice: 230, image: 'https://via.placeholder.com/100' },
      { id: '3-2', name: 'Salmon', price: 800, discountPrice: 750, image: 'https://via.placeholder.com/100' },
      { id: '3-3', name: 'Beef', price: 600, discountPrice: 550, image: 'https://via.placeholder.com/100' },
      { id: '3-4', name: 'Prawns', price: 700, discountPrice: 650, image: 'https://via.placeholder.com/100' },
      { id: '3-5', name: 'Turkey', price: 350, discountPrice: 320, image: 'https://via.placeholder.com/100' },
      { id: '3-6', name: 'Cod', price: 500, discountPrice: 480, image: 'https://via.placeholder.com/100' },
      { id: '3-7', name: 'Lamb Chops', price: 700, discountPrice: 650, image: 'https://via.placeholder.com/100' },
      { id: '3-8', name: 'Tuna', price: 750, discountPrice: 700, image: 'https://via.placeholder.com/100' },
      { id: '3-9', name: 'Shrimp', price: 400, discountPrice: 380, image: 'https://via.placeholder.com/100' },
      { id: '3-10', name: 'Crab', price: 900, discountPrice: 850, image: 'https://via.placeholder.com/100' },
    ],
  },
  {
    id: '4',
    name: 'Bakery & Snacks',
    image: require("../../../assets/homepage/category/backery.png"),
    products: [
      { id: '4-1', name: 'Bread', price: 40, discountPrice: 35, image: 'https://via.placeholder.com/100' },
      { id: '4-2', name: 'Croissant', price: 60, discountPrice: 55, image: 'https://via.placeholder.com/100' },
      { id: '4-3', name: 'Muffin', price: 50, discountPrice: 45, image: 'https://via.placeholder.com/100' },
      { id: '4-4', name: 'Cookies', price: 30, discountPrice: 25, image: 'https://via.placeholder.com/100' },
      { id: '4-5', name: 'Donuts', price: 70, discountPrice: 65, image: 'https://via.placeholder.com/100' },
      { id: '4-6', name: 'Cake', price: 200, discountPrice: 180, image: 'https://via.placeholder.com/100' },
      { id: '4-7', name: 'Brownies', price: 80, discountPrice: 75, image: 'https://via.placeholder.com/100' },
      { id: '4-8', name: 'Cupcakes', price: 90, discountPrice: 85, image: 'https://via.placeholder.com/100' },
      { id: '4-9', name: 'Scones', price: 60, discountPrice: 55, image: 'https://via.placeholder.com/100' },
      { id: '4-10', name: 'Pretzels', price: 40, discountPrice: 35, image: 'https://via.placeholder.com/100' },
    ],
  },
  {
    id: '5',
    name: 'Dairy & Eggs',
    image: require("../../../assets/homepage/category/milk.png"),
    products: [
      { id: '5-1', name: 'Whole Milk', price: 50, discountPrice: 45, image: 'https://via.placeholder.com/100' },
      { id: '5-2', name: 'Skimmed Milk', price: 45, discountPrice: 40, image: 'https://via.placeholder.com/100' },
      { id: '5-3', name: 'Organic Eggs', price: 60, discountPrice: 55, image: 'https://via.placeholder.com/100' },
      { id: '5-4', name: 'Free Range Eggs', price: 55, discountPrice: 50, image: 'https://via.placeholder.com/100' },
      { id: '5-5', name: 'Goat Milk', price: 70, discountPrice: 65, image: 'https://via.placeholder.com/100' },
      { id: '5-6', name: 'Buttermilk', price: 40, discountPrice: 35, image: 'https://via.placeholder.com/100' },
      { id: '5-7', name: 'Egg White', price: 45, discountPrice: 40, image: 'https://via.placeholder.com/100' },
      { id: '5-8', name: 'Egg Yolk', price: 50, discountPrice: 45, image: 'https://via.placeholder.com/100' },
      { id: '5-9', name: 'Almond Milk', price: 80, discountPrice: 75, image: 'https://via.placeholder.com/100' },
      { id: '5-10', name: 'Soy Milk', price: 55, discountPrice: 50, image: 'https://via.placeholder.com/100' },
    ],
  },
  {
    id: '6',
    name: 'Beverages',
    image: require("../../../assets/homepage/category/beverage.png"),
    products: [
      { id: '6-1', name: 'Orange Juice', price: 100, discountPrice: 90, image: 'https://via.placeholder.com/100' },
      { id: '6-2', name: 'Apple Juice', price: 90, discountPrice: 80, image: 'https://via.placeholder.com/100' },
      { id: '6-3', name: 'Cola', price: 40, discountPrice: 35, image: 'https://via.placeholder.com/100' },
      { id: '6-4', name: 'Lemonade', price: 30, discountPrice: 25, image: 'https://via.placeholder.com/100' },
      { id: '6-5', name: 'Ginger Ale', price: 50, discountPrice: 45, image: 'https://via.placeholder.com/100' },
      { id: '6-6', name: 'Sparkling Water', price: 60, discountPrice: 55, image: 'https://via.placeholder.com/100' },
      { id: '6-7', name: 'Iced Tea', price: 70, discountPrice: 65, image: 'https://via.placeholder.com/100' },
      { id: '6-8', name: 'Milkshake', price: 120, discountPrice: 100, image: 'https://via.placeholder.com/100' },
      { id: '6-9', name: 'Energy Drink', price: 150, discountPrice: 140, image: 'https://via.placeholder.com/100' },
      { id: '6-10', name: 'Coconut Water', price: 80, discountPrice: 70, image: 'https://via.placeholder.com/100' },
    ],
  },
];

export const background_categories = {
  1: { backgroundColor: 'rgba(83, 177, 117, 0.3)', borderColor: '#53B175' },
  2: { backgroundColor: 'rgba(248, 164, 76, 0.3)', borderColor: '#F8A44C' },
  3: { backgroundColor: 'rgba(247, 165, 147, 0.3)', borderColor: '#F7A593' },
  4: { backgroundColor: 'rgba(211, 176, 224, 0.3)', borderColor: '#D3B0E0' },
  5: { backgroundColor: 'rgba(253, 229, 152, 0.3)', borderColor: '#FDE598' },
  6: { backgroundColor: 'rgba(183, 223, 245, 0.3)', borderColor: '#B7DFF5' },
}




